---
#
# Default CSV export/import configuration.
#
# TODO this should also be supported by the CSV export
# TODO allow for column labels
# TODO support configuring special import/export handlers (conversion of values)
# TODO support named collection/licence/... mapping (e.g. 'CCBY' = 4)
# TODO support identifying collections with ROLENAME:OAINAME
# TODO support debugging (report ignored columns)
# TODO support converting header to config and back (for auto config debugging)
# TODO extend CvsCommand for new features like config-file, auto-mode and such
# TODO support global options/defaults
#
# default requires 33 columns
#
# Supported attributes:
# - multiValue
# - columns
# - label (default: field name)
# - type
# - required (default: false)
# - ignore
#

# Specific identifier type in a single column
Identifier-Old:

# Simple Document fields
Language:
Type:
ServerState:

# Main titles
Title-Main:
  columns:
    Language:
    Value:

# Abstracts
Title-Abstract:
  multiValue: true
  columns:
    Language:
    Value:

# Process all title types
Title:
  columns:
    Type:
    Language:
    Value:

Person:
  multiValue: true
  columns:
    Role:
    FirstName:
    LastName:

# Dates
Date:
  columns:
    Type:
    Value:

Identifier:
  multiValue: true # TODO add support
  columns:
    Type:
    Value:

# TODO
Note:
  columns:
    Visibility:
    Message:

# TODO currently collections are not setup for testing - fix!
Collection:
  multiValue: true

# TODO
Series:
  multiValue: true
  
Volume:

Licence-Id:

# TODO is currently ignored
Enrichment:
  multiValue: true

Enrichment-availability:
Enrichment-Format:
Enrichment-KindOfPublication:
Enrichment-IdNo:
Enrichment-CopyrightPrint:
Enrichment-CopyrightEBook:
Enrichment-Relevance:

# TODO "Filename"
File:
