---
#
# Default CSV export/import configuration.
#
# TODO this should also be supported by the CSV export
# TODO allow for column labels
# TODO support configuring special import/export handlers (conversion of values)
# TODO support named collection/licence/... mapping (e.g. 'CCBY' = 4)
# TODO support identifying collections with ROLENAME:OAINAME
# TODO support debugging (report ignored columns)
# TODO support converting header to config and back (for auto config debugging)
# TODO extend CvsCommand for new features like config-file, auto-mode and such
#
# default requires 33 columns
#
# Supported attributes:
# - multiValue
# - columns
# - label (default: field name)
# - type
# - required (default: false)
# - ignore
#
# TODO create unit test for this format
#


# Specific identifier type in a single column
Identifier-Old:
Language:
Type:
ServerState:

# TODO
TitleMain:
  columns:
    Language:
    Value:

# TODO
TitleAbstract:
  multiValue: true
  columns:
    Language:
    Value:

# TODO Titles is no field - requires special handling
Titles:
  class: opus.import.csv.CsvTitlesProcessor
  columns:
    Type:
    Language:
    Value:

# TODO
Person:
  multiValue: true
  columns:
    Type:
    FirstName:
    LastName:

# TODO
Date:
  columns:
    Type:
    Value:

Identifier:
  multiValue: true # TODO add support
  columns:
    Type:
    Value:

# TODO
Note:
  columns:
    Visibility:
    Value:
  
Collection2:
  multiValue: true

# TODO
Series:
  multiValue: true
  
Volume:

Licence-Id:

# TODO is currently ignored
Enrichments:
  multiValue: true

Enrichment-Availability:
Enrichment-Format:
Enrichment-KindOfPublication:
Enrichment-IdNo:
Enrichment-CopyrightPrint:
Enrichment-CopyrightEBook:
Enrichment-Relevance:

# TODO
Filename:
